version = 0.1

[default.build.parameters]
use_container = false

[default.deploy.parameters]
stack_name = "secretary-bot"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "AlertEmail=\"\""